apiVersion: backstage.io/v1beta2
kind: Template
metadata:
  name: end-to-end-microservice
  title: End to End Microservice Scaffold
  description: |
    Creates a project and sets it up in a repo and Jenkins
spec:
  owner: backstage/techdocs-core
  type: service
  parameters:
    - title: Enter project details
      required:
        - component_id
        - owner
        - java_package_name
      properties:
        component_id:
          title: Name
          type: string
          description: Unique name of the component
        java_package_name:
          title: Java Package Name
          type: string
          description: Name for the java package. eg (io.backstage.blah)
        description:
          title: Description
          type: string
          description: Help others understand what this website is for.
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowedKinds: 
              - Group
    - title: Choose a location  
      required:
        - repoUrl
      properties: 
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com
    - title: Enter Jenkins Details
      required:
        - projectName
      properties:
        projectName:
          title: Project Name
          type: string
          description: Unique name for project
          ui:autofocus: true
          ui:options:
            rows: 5
        jenkinsFile:
          title: Jenkins Build file
          type: string
          description: location of the Jenkinsfile in the project relative to the project root
        credentialsId:
          title: Jenkins Credentials Identifier
          type: string
          description: Identifier for credentials in Jenkins to enable connectivity to the SCM Server.

  steps:
    - id: template
      name: Fetch Skeleton + Template
      action: fetch:template
      input:
        url: ./skeleton
        copyWithoutRender:
          - .github/workflows/*
        values:
          component_id: '{{ parameters.component_id }}'
          description: '{{ parameters.description }}'
          artifact_id: '{{ parameters.component_id }}'
          java_package_name: '{{ parameters.java_package_name }}'
          owner: '{{ parameters.owner }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          http_port: 8080
    - id: publish
      name: Publish to SCM
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: 'This is {{ parameters.component_id }}'
        repoUrl: '{{ parameters.repoUrl }}'
        repoVisibility: 'public'
    - id: fetch-job-template
      name: Create Jenkins config from Template
      action: fetch:template
      input:
        url: ./jenkins
        targetPath: ./config-output
        values:
          description: 'This is {{ parameters.component_id }}'
          jobName: '{{ parameters.projectName }}'
          destination: '{{ parseRepoUrl parameters.repoUrl }}'
          scmId: '123456'
          jenkinsFile: '{{ parameters.jenkinsFile }}'
          credentialsId: '{{ parameters.credentialsId }}'
    - id: create-jenkins-job
      name: Create Jenkins Job
      action: nationalgrid:create-jenkins-job
      input:
        projectName: '{{ parameters.projectName }}'
        jobFile: './config-output/multi-branch.xml'

  output:
    remoteUrl: '{{ steps.fetch-project.output.remoteUrl }}'

